# Generated by Django 2.1 on 2018-08-27 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brewery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=2)),
                ('description', models.TextField()),
                ('website_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atmosphere', models.PositiveIntegerField()),
                ('beer_tenders', models.PositiveIntegerField()),
                ('beer_selection', models.PositiveIntegerField()),
                ('notes', models.TextField()),
                ('brewery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='brew_review.Brewery')),
            ],
        ),
    ]
