# Generated by Django 2.1 on 2018-10-25 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew_review', '0002_review_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brewery',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='brewery',
            name='website_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
