# Generated by Django 2.1 on 2018-10-25 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew_review', '0003_auto_20181025_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
