# Generated by Django 2.1 on 2018-10-25 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew_review', '0004_auto_20181025_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='photo',
            field=models.TextField(blank=True),
        ),
    ]
