# Generated by Django 2.1 on 2018-10-28 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brew_review', '0005_auto_20181025_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='photo',
        ),
    ]
