# Generated by Django 2.1 on 2018-10-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew_review', '0006_remove_review_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='brewery',
            name='photo_url',
            field=models.TextField(default='https://placeholdit.imgix.net/~text?txtsize=33&txt=256%C3%97180&w=256&h=180'),
        ),
    ]
